# Generated by Django 5.2 on 2025-05-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_login_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='staff',
        ),
    ]
