# Generated by Django 5.1.5 on 2025-07-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_order_child_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_master',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Order_Child',
        ),
        migrations.DeleteModel(
            name='Order_Master',
        ),
    ]
