# Generated by Django 5.2 on 2025-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('pho', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('photo', models.FileField(upload_to='file')),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
