# Generated by Django 5.2 on 2025-06-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_remove_login_staff'),
        ('Staffapp', '0001_initial'),
        ('Userapp', '0002_order_child_user_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user_products')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.reg')),
            ],
        ),
    ]
